[package]
name = "konnektoren-api"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "konnektoren-api"
path = "src/main.rs"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower = "0.4"

utoipa = { version = "4.2.3", features = ["axum_extras"], optional = true }
utoipa-swagger-ui = { version = "5", features = ["axum"], optional = true }
log = "0.4.21"

[features]
default = ["openapi"]
openapi = ["utoipa", "utoipa-swagger-ui"]
