version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/konnektoren/konnektoren-api:latest
    environment:
      - RUST_LOG=${LOG_LEVEL}
      - MNEMONIC=${MNEMONIC}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - FAUCET_ADDRESS=${FAUCET_ADDRESS}
      - REDIS_URL=redis://redis:6379
      - ENABLE_TELEMETRY=${ENABLE_TELEMETRY:-false}
      - JAEGER_ENDPOINT=${JAEGER_ENDPOINT:-http://jaeger:14268/api/traces}
    #ports:
    #  - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

  telegram_bot:
    profiles:
      - telegram
    image: konnektoren-telegram-bot
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=${LOG_LEVEL}
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ./redis-data:/data

  cloudflared:
    profiles:
      - cloudflare
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    environment:
      - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    depends_on:
      - server

  matchbox:
    profiles:
      - matchbox
    image: jhelsing/matchbox-server:v0.10.0
    environment:
      - MATCHBOX_SERVER_PORT=3536

  jaeger:
    profiles:
      - tracing
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
