global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape the OpenTelemetry metrics from Jaeger
  - job_name: "otel"
    static_configs:
      - targets: ["jaeger:8889"] # OpenTelemetry Collector metrics port
    metrics_path: "/metrics"

  # Scrape Jaeger's own metrics
  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]
