global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "konnektoren"
    static_configs:
      - targets: ["konnektoren-api:3000"]
    metrics_path: "/metrics"

  # Scrape Jaeger's own metrics
  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]
