global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "otlp"
    static_configs:
      - targets: ["jaeger:4318"]
    metrics_path: "/metrics"

  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:14269"]
